backend:
  name: git-gateway
  repo: LasseKrarup/TheHideout
  branch: main

media_folder: static/img
public_folder: /img

# Disables preview editor
editor:
  preview: false

# Collections
# https://www.netlifycms.org/docs/collection-types/
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Front Page"
        file: "content/pages/index.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          - label: Studio Section
            name: studio
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          - label: Video Section
            name: video
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          - label: Photo Section
            name: photo
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
      - name: "studio"
        label: "Studio Page"
        file: "content/pages/studio/index.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          - label: Price examples
            name: priceExamples
            widget: list
            summary: "{{fields.title}}"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Example price, name: price, widget: string }
      - name: "recording"
        label: "Studio: Recording"
        file: "content/pages/studio/recording.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
      - name: "livesessions"
        label: "Studio: Live Sessions"
        file: "content/pages/studio/livesessions.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
      - name: "streaming"
        label: "Studio: Streaming"
        file: "content/pages/studio/streaming.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
      - name: "video"
        label: "Video Page"
        file: "content/pages/video/index.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          - label: Price examples
            name: priceExamples
            widget: list
            summary: "{{fields.title}}"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Example price, name: price, widget: string }
      - name: "musicvideos"
        label: "Video: Music Videos"
        file: "content/pages/video/musicvideos.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
      - name: "promotion"
        label: "Video: Promotion"
        file: "content/pages/video/promotion.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
      - name: "photography"
        label: "Photography Page"
        file: "content/pages/photoghraphy/index.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
          - label: Price examples
            name: priceExamples
            widget: list
            summary: "{{fields.title}}"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Example price, name: price, widget: string }
      - name: "business"
        label: "Photography: Business"
        file: "content/pages/photography/business.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
      - name: "concertphotography"
        label: "Photography: Concert Photography"
        file: "content/pages/photography/concertphotography.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
      - name: "about"
        label: "About Page"
        file: "content/pages/about/index.md"
        fields:
          - label: Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }
      - name: "contact"
        label: "About: Contact"
        file: "content/pages/about/contact.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
      - name: "pricing"
        label: "About: Pricing"
        file: "content/pages/about/pricing.md"
        fields:
          - label: Welcome Section
            name: welcome
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Content, name: content, widget: markdown }
          - label: Price examples
            name: priceExamples
            widget: list
            summary: "{{fields.title}}"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Example price, name: price, widget: string }
